import { useEffect, useRef, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { AnimatePresence, motion } from 'framer-motion';
import { CloseIcon, HomeIcon, LibraryIcon, MenuIcon, PoemsIcon, SearchIcon, StoriesIcon, StoreIcon } from '../icons';
import api from '../../api/axios';

const navItems = [['/', 'Home', HomeIcon], ['/stories', 'Stories', StoriesIcon], ['/poems', 'Poems', PoemsIcon], ['/library', 'Library', LibraryIcon], ['/store', 'Store', StoreIcon]];

export default function Navbar() {
  const navigate = useNavigate();
  const [user, setUser] = useState(null); const [menu, setMenu] = useState(false); const [searchOpen, setSearchOpen] = useState(false);
  const [query, setQuery] = useState(''); const [results, setResults] = useState({ stories: [], authors: [] }); const [loading, setLoading] = useState(false); const input = useRef(null);
  useEffect(() => { try { setUser(JSON.parse(localStorage.getItem('user') || 'null')); } catch { setUser(null); } }, []);
  useEffect(() => { if (!searchOpen) return undefined; input.current?.focus(); const close = (event) => event.key === 'Escape' && setSearchOpen(false); window.addEventListener('keydown', close); return () => window.removeEventListener('keydown', close); }, [searchOpen]);
  useEffect(() => { const value = query.trim(); if (!value) { setResults({ stories: [], authors: [] }); return undefined; } const timer = setTimeout(async () => { setLoading(true); try { const { data } = await api.get('/stories/search', { params: { q: value, sort: 'popular' } }); setResults(data); } catch { setResults({ stories: [], authors: [] }); } finally { setLoading(false); } }, 220); return () => clearTimeout(timer); }, [query]);
  const submit = (event) => { event.preventDefault(); if (!query.trim()) return; setSearchOpen(false); navigate(`/search?q=${encodeURIComponent(query.trim())}`); };
  const logout = () => { localStorage.removeItem('token'); localStorage.removeItem('user'); setUser(null); navigate('/'); };
  return <><nav className="netflix-nav"><Link to="/" className="logo"><StoriesIcon size={28} color="#E50914" /> Story<span>Teller</span></Link><div className="nav-links">{navItems.map(([to,label,Icon]) => <Link key={to} to={to}><Icon size={17} color="#B3B3B3" /> {label}</Link>)}{user?.role === 'ADMIN' && <Link to="/admin">Studio</Link>}</div><div className="nav-actions"><button className="search-btn" aria-label="Search" onClick={() => setSearchOpen(true)}><SearchIcon size={20} color="#B3B3B3" /></button>{user ? <button className="account-btn" onClick={logout} title="Sign out">{user.name?.[0] || 'U'}</button> : <><Link className="nav-signin" to="/login">Sign In</Link><Link className="nav-signup" to="/register">Sign Up</Link></>}<button className="mobile-menu-btn" onClick={() => setMenu(!menu)}>{menu ? <CloseIcon size={24} /> : <MenuIcon size={24} />}</button></div></nav>{menu && <div className="mobile-nav">{navItems.map(([to,label]) => <Link key={to} to={to} onClick={() => setMenu(false)}>{label}</Link>)}{user?.role === 'ADMIN' && <Link to="/admin" onClick={() => setMenu(false)}>Studio</Link>}{user && <Link to="/profile" onClick={() => setMenu(false)}>Profile</Link>}</div>}<AnimatePresence>{searchOpen && <motion.div className="search-overlay" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onMouseDown={(event) => event.target === event.currentTarget && setSearchOpen(false)}><form className="search-dialog" onSubmit={submit}><SearchIcon size={20} color="#aaa5b3" /><input ref={input} className="search-input" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search stories, poems, authors, genres…" />{query && <button type="button" className="search-clear" onClick={() => setQuery('')} aria-label="Clear search">×</button>}<button className="search-submit">Search</button>{query && <div className="search-suggestions">{loading ? <p>Searching the library…</p> : results.stories?.length || results.authors?.length ? <>{results.authors?.length > 0 && <div><b>Authors</b>{results.authors.slice(0,3).map(author => <button type="button" key={author} onClick={() => { setQuery(author); }}>{author}</button>)}</div>}<div><b>Stories & poems</b>{results.stories.slice(0,6).map(story => <button type="button" key={story.id} onClick={() => { setSearchOpen(false); navigate(`/stories/${story.id}`); }}><span>{story.title}</span><small>{story.category} · {story.author}</small></button>)}</div></> : <p>No results found. Try another search.</p>}</div>}</form><button className="search-close" onClick={() => setSearchOpen(false)} aria-label="Close search"><CloseIcon size={24} /></button></motion.div>}</AnimatePresence></>;
}
