import { useEffect, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import api from '../api/axios';
import StoryCard from '../components/ui/StoryCard';

export default function Search() {
  const [params,setParams]=useSearchParams(), [query,setQuery]=useState(params.get('q')||''), [result,setResult]=useState({stories:[],authors:[],total:0}), [loading,setLoading]=useState(false);
  const type=params.get('type')||'all',sort=params.get('sort')||'popular',genre=params.get('genre')||'All',status=params.get('status')||'All';
  useEffect(()=>{const q=params.get('q')?.trim();if(!q){setResult({stories:[],authors:[],total:0});return;}setLoading(true);api.get('/stories/search',{params:{q,type,sort,genre,status}}).then(({data})=>setResult(data)).catch(()=>setResult({stories:[],authors:[],total:0})).finally(()=>setLoading(false));},[params,type,sort,genre,status]);
  const update=(key,value)=>setParams({q:params.get('q')||query,type,sort,genre,status,[key]:value}); const submit=e=>{e.preventDefault();setParams({q:query,type,sort,genre,status});}; const empty=!result.stories.length&&!result.authors.length;
  return <main className="search-page"><header><p className="admin-eyebrow">Discover</p><h1>Search StoryTeller</h1><form onSubmit={submit}><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Stories, poems, authors, genres…"/><button type="button" onClick={()=>{setQuery('');setParams({});}}>Clear</button><button>Search</button></form></header><div className="search-controls"><select value={type} onChange={e=>update('type',e.target.value)}><option value="all">All</option><option value="stories">Stories</option><option value="poems">Poems</option><option value="authors">Authors</option></select><select value={genre} onChange={e=>update('genre',e.target.value)}><option>All</option><option>Romance</option><option>Fantasy</option><option>Mystery</option><option>Poetry</option></select><select value={status} onChange={e=>update('status',e.target.value)}><option>All</option><option>Completed</option><option>Ongoing</option></select><select value={sort} onChange={e=>update('sort',e.target.value)}><option value="popular">Most Read</option><option value="rating">Highest Rated</option><option value="newest">Newest</option><option value="az">A-Z</option></select></div>{loading?<p className="search-state">Searching the library…</p>:!params.get('q')?<p className="search-state">Search titles, authors, genres, and poems.</p>:empty?<div className="search-state"><h2>No results found</h2><p>Try another search.</p></div>:<><p className="search-result-count">{result.total} result{result.total===1?'':'s'} for “{params.get('q')}”</p>{result.authors.length>0&&<section className="author-results"><strong>Authors</strong>{result.authors.map(author=><span key={author}>{author}</span>)}</section>}<div className="search-grid">{result.stories.map((story,index)=><StoryCard key={story.id} story={story} index={index}/>)}</div></>}</main>;
}
